name: Build and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Packages
        run: |
          npm install
      - name: Build the project
        run: npm run build
      - name: Install the Lighthouse CI CLI.
        run: npm install -g @lhci/cli
      - name: Run Lighthouse
        run: lhci autorun --config=./lighthouserc.js
