name: Lighthouse CI
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Start a local server
      - name: Serve the app
        run: npm run start &

      - name: Sleep for 10 seconds to allow http-server to start
        run: sleep 10

      # - name: Check App
      #   run: curl http://localhost:3000

      # # Run Lighthouse against the local server
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: "http://localhost:3000"
          config-path: "./lighthouse.json"
          temporaryPublicStorage: true
